# Generated by Django 5.1.1 on 2026-04-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': [models.OrderBy(models.F('pub_date'), descending=True, nulls_last=True)], 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
